name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build App
      run: |
        # Build for release without code signing
        xcodebuild -scheme recordme -configuration Release -derivedDataPath ./build build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    
    - name: Create DMG
      run: |
        # Find the built app
        APP_PATH=$(find ./build -name "recordme.app" -type d | head -1)
        
        if [ ! -d "$APP_PATH" ]; then
          echo "App not found after build"
          exit 1
        fi
        
        # Create a temporary DMG directory
        mkdir -p dmg-temp
        cp -R "$APP_PATH" dmg-temp/RecordMe.app
        
        # Create DMG
        hdiutil create -volname "RecordMe" -srcfolder dmg-temp -ov -format UDZO RecordMe.dmg
    
    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          RecordMe.dmg
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}