name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build App
      run: |
        xcodebuild -scheme recordme -configuration Release -derivedDataPath ./build -archivePath ./build/recordme.xcarchive archive
        xcodebuild -exportArchive -archivePath ./build/recordme.xcarchive -exportPath ./build/export -exportOptionsPlist ./ExportOptions.plist
    
    - name: Create DMG
      run: |
        # Create a temporary DMG directory
        mkdir -p dmg-temp
        cp -R "./build/export/recordme.app" dmg-temp/
        
        # Create DMG
        hdiutil create -volname "RecordMe" -srcfolder dmg-temp -ov -format UDZO RecordMe.dmg
    
    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          RecordMe.dmg
          ./build/export/recordme.app
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}